### ISSUE TITLE
Error on saving changes.

### ISSUE THREAD

**Issue by CameronW1** [SkiTles55/SPT-AKI-Profile-Editor#102]
**Versions**
- SPT 3.7.0
- PE v:2.7
- No mods, not before, not during/after

**Describe the bug**
When editing a profile, I go and change a single stat or a whole bunch of stats or set quest progress to anything. Anyways when I go to save I get an error about a value can't be null ("0")

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
[635b999f2aa918a84d872222.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12388941/635b999f2aa918a84d872222.zip)

**Comment by CameronW1** [comment]
When using the profile editor with older Bleeding edge versions I never got this error, even if I give myself a single point of xp, it'll happen.

**Comment by CameronW1** [comment]
I figured, since I might get asked, I did reinstall it. No luck.

**Comment by SkiTles55** [comment]
Bleeding edge versions never been supported. Wait for stable release. After that PE will be updated

**Comment by CameronW1** [comment]
> Bleeding edge versions never been supported. Wait for stable release. After that PE will be updated

Works perfectly fine with 3.6.0 BE (tested again to be sure I wasn't wrong) . *shrugs* Anyways, I look forward to the next stable profile editor nonetheless.
