### ISSUE TITLE
Setting any quest to "AvailableForFinish" unlocks a number of new quests out of sequence

### ISSUE THREAD

**Issue by DerManuFS** [SkiTles55/SPT-AKI-Profile-Editor#105]
*edit*: additional info in comment below as I can't change the title!

**Versions**
- SPT-AKI Server version: 3.6.1 (fresh install via AKI Installer)
- SPT-AKI Profile Editor version: 2.7
- List of installed mods: none

**Describe the bug**
When editor is used to set any quest to "AvailableForFinish" it unlocks a number of new quests out of sequence:
Prapor: Tourists
Therapist: Important Patient
Fence: The TerraGroup Trail - Part 1
Skier: Cocktail Tasting, Hint
Peacekeeper: Hustle
Mechanic: Failed setup
Also maybe some on Jaeger, but tested this on a fresh profile, Jaeger wasn't unlocked yet

It also seems to break something quest-related as when finishing a quest, any direct follow up quests do not get listed immediately (I have to switch to buy/sell and back to quests to see the new unlocked quest).

Also when finishing a quest I get a *lot* of messages about unrelated quests. This list gets longer and longer the more quests I finish, regularly or otherwise. The sceenshot shows the messages I got when I finished the below mentioned Debut quest:
![messages](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/97910305/ccef1ec9-f6d9-44a9-8dcd-86198d00d8e5)

**Additional context**
The attached profile is a freshly created profile where I only accepted the 2 starting quests and then used the profile editor to set Prapor's Debut quest to AvailableForFinish. This then unlocked the above mentioned quests.
[15d540ccdd66bceea7298595.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12443547/15d540ccdd66bceea7298595.zip)

I noticed this behavior on my heavily modded server and then did this fresh install without mods to verify. It happened on both instances, with the attached fresh profile and my many-hours-heavy-mods profile. The list of unlocked quests seems to be the same in both instances.

Cheers!

**Comment by DerManuFS** [comment]
On a whim I just tested something else. It's not just changing quests to another status. It happens even if I only open the profile in the Editor, change nothing, and click save.
Simply saving with no changes made also leads to the above described bug and behavior.

**Comment by SkiTles55** [comment]
Can't be fixed. That is server bahaviour.
All this quests is  for events, and they don't have conditions for "AvailableForStart" in server db.
So, after adding them via profile editor with status "Locked", server changes their status to "AvailableForStart"

Only one way for avoid that - disabling "Adding missing quests to the profile" in profile editor settings

**Comment by DerManuFS** [comment]
Might I then suggest having that option disabled by default? I was not aware of this behavior and it's not in the description of the tool. :)

**Comment by SkiTles55** [comment]
This option is disabled by default, so you enabled it on by yourself
