### ISSUE TITLE
When i tried to install it says "unexpected error"

### ISSUE THREAD

**Issue by Skif069** [SkiTles55/SPT-AKI-Profile-Editor#107]
**Versions**
- SPT-AKI Server version: 3.6.1
- SPT-AKI Profile Editor: version 2.7
- List of installed mods: nothing

**Describe the bug**
![image](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/143666537/dcfc821f-242c-4b67-9516-6ee0ae65a54b)

**Comment by SkiTles55** [comment]
That is windows error, not related to editor or installer. May be that will help - https://answers.microsoft.com/en-us/windows/forum/all/error-code-2503-and-2502/8cdaeea6-f775-458a-9a73-71424bcdb412
