### ISSUE TITLE
I can’t add items to the stash because he doesn’t see and writes messages. Object reference not set an instance od an object

### ISSUE THREAD

**Issue by NadaraGod** [SkiTles55/SPT-AKI-Profile-Editor#109]
[log10-09-2023.txt](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12570188/log10-09-2023.txt)

**Comment by SkiTles55** [comment]
Bug report not filled correctly. Create new issue, filled as in template, with details and steps for reproduce
