### ISSUE TITLE
Editor throwing error when trying to add items/money.

### ISSUE THREAD

**Issue by MrRetr0** [SkiTles55/SPT-AKI-Profile-Editor#112]
- SPT-AKI Server version 3.6.1
- SPT-AKI Profile Editor version 2.7
- List of installed mods:
 Use Items anywhere
Expanded Task Text (ETT)
Painter
Mag Tape
Actual Sick SICC
SandCore: FDE Retextures
The Little Drummer Boy
BlackCore
Fifty Shades of Boomer
Fontaine's Red Dot Tweaker
EFT SCOPE AND RED DOT SIGHT OVERHAUL BY GEFF HANNIGAN - Reupload
Small Cases - Now With Fannypack!
Rogue Justice: Punishing Tarkov (The Punisher Boss Mod)
WhiteCore
Search Open Containers
GreenCore
Two Slot Extended Mags
USEC-Commander
RedCore
BigBrain
Definitive Retexture Immersion Project (DRIP)
MoreCheckmarks
Backdoor Bandit (BB)
Waypoints - Expanded Bot Patrols and Navmesh
Task List Fixes
Deadly Blades
Looting Bots
Visceral Dismemberment
Boop's Quest Zone API
Bootlegger
Goblin King
SERVPH's Tarky Menu
FU Inertia
Visceral Bodies
Amands's Graphics
Amands's Hitmarker
Game Panel HUD
SPT Realism Mod
KMC Server Value Modifier (SVM)
JustNU Core
SPT-Aki Profile Editor

Every time I attempt to add an item/money, the Editor gives me an error stating that an "Item added by mod found. Use the section "Cleaning from Mods" to remove such items". Issue is, there are not modded items directly in my stash. They are only some in my PMC inventory, and others are in bags in the stash, but not directly in the stash itself. The editor shows no items with a red triangle icon to indicate what item it thinks is the issue. 

SPT-AKI Profile file
[SPT profile file.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12764499/SPT.profile.file.zip)

**Comment by SkiTles55** [comment]
You have item with TPL 01016_AK_PT_1_STOCK in inventory. That item added by mod, and inserted in some weapon in your stash. You can remove that item in "Cleaning from mods" tab, or using Helper mod for ability to work with modded items - https://github.com/SkiTles55/SPT-AKI-Profile-Editor/blob/master/Guidelines/ModHelperENG.md
