### ISSUE TITLE
Value Cannot Be Null (Parameter 'o')

### ISSUE THREAD

**Issue by tugberksncktr04** [SkiTles55/SPT-AKI-Profile-Editor#113]
**Versions**
- SPT-AKI Server version : 3.7.0
- SPT-AKI Profile Editor version : 2.7
- List of installed mods : ServerValueModifier

**Describe the bug**
I am getting the error you see on the screen.

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

![image](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/63294989/3f0b721d-1dc7-469d-b29c-a6125bb07544)

**Comment by SkiTles55** [comment]
no support for SPT-AKI BE builds
