### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Nate25561** [SkiTles55/SPT-AKI-Profile-Editor#114]
**Versions**
- SPT-AKI Server version 3.7.0
- SPT-AKI Profile Editor version 2.8
- List of installed mods

-bluehead aio
- joshj5hawk super ammo and super items
-keep your equipment
- priscilu and priscilu extra items
- gigachad profile
- door breacher
-ms stola
- all clothes rai rai
- black module armoured vests
- hephaestus 
- just nu core
- pnk gear
- saria shop

**Describe the bug**
Whenever I attempt to save any change, I'm greeted with the message:
"Error
Object reference not set to an instance of an object"

In particular changing all the quests to success.

**Additional context**
SPT-AKI Profile file

[d865a389504c0131606fb51e.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12875675/d865a389504c0131606fb51e.json)

**Comment by Nate25561** [comment]
Extra note, I've tried this with default profiles from SPK and get the same error.

**Comment by CleetusMcYeetus** [comment]
I'm having the same issue that Nate 25561 descibed.

**Comment by SkiTles55** [comment]
Fixed
