### ISSUE TITLE
Another bug report

### ISSUE THREAD

**Issue by Nate25561** [SkiTles55/SPT-AKI-Profile-Editor#115]
Versions

SPT-AKI Server version 3.7.0
SPT-AKI Profile Editor version 2.8

List of installed mods
bluehead aio

joshj5hawk super ammo and super items
keep your equipment
priscilu and priscilu extra items
gigachad profile
door breacher
ms stola
all clothes rai rai
black module armoured vests
hephaestus
just nu core
pnk gear
saria shop

Describe the bug
Whenever I try to set my level or change quests, I now get a different error.

https://gyazo.com/288ca1eafc6cd004e2d1396c629825b1
https://gyazo.com/73f0990f145466c52e44b8e2ecab24fb

In order of errors showing on save profile.

I used a different profile which was the SPK developer profile and got the errors.

Additional context
SPT-AKI Profile file

[a802ecaf8647cbf6ebc45a5e.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12884103/a802ecaf8647cbf6ebc45a5e.json)

**Comment by SkiTles55** [comment]
Setting "Default action for profile issues" in settings to "Always ignore" must help. Later i will fix that

**Comment by Nate25561** [comment]
I've tried setting it to the setting you suggested, it still shows the same error, furthermore the helper mod doesn't do anything either.

I'm fine with waiting, I Just want you to know of the errors that are happening. 

Love your work.

**Comment by SkiTles55** [comment]
Fixed. Will be in next release
