### ISSUE TITLE
Merchant levels wont change

### ISSUE THREAD

**Issue by MurdersInc828** [SkiTles55/SPT-AKI-Profile-Editor#116]
**Versions**
- SPT-AKI Server version 3.7.0
- SPT-AKI Profile Editor version 2.8.1
- List of installed mods No mods installed

**Describe the bug**
Trader level changes does not effect in game even though I saved it.
+ merchant levels resets whenever I open the editor app. I also change the hideout levels through the editor app but no issues there.

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
[7c99c8958f97817a727a8895.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12903469/7c99c8958f97817a727a8895.json)

**Comment by SkiTles55** [comment]
Don't see problems with saving.

But trader level changing needs also PMC level changing for affect game - https://github.com/SkiTles55/SPT-AKI-Profile-Editor/blob/master/ENGFAQ.md#traders-levels-are-not-saved
