### ISSUE TITLE
Cant add any items.

### ISSUE THREAD

**Issue by littledrymuffin** [SkiTles55/SPT-AKI-Profile-Editor#118]
**Versions**
3.6.1
2.7
AUG_AttachmentPack","MC-LMG","serwolfik-Heavy_Ttrooper","Platinum-TheBlacklist-1.3.0","Realistic-FLIR-RS32-1.4.2","Realistic-Reap-ir-1.0.2","Tracer","Priscilu","zz-riku8405-contentport-0.17.9","zzDrakiaXYZ-Waypoints","ServerValueModifier

**Describe the bug**
anytime i add an item it gives me error saying. item added by mod found. use section "cleaning from mods" to remove such item.

**Additional context**
SPT-AKI Profile file
[514d7cb945aa25c8e778bd43.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/12920819/514d7cb945aa25c8e778bd43.zip)

**Comment by SkiTles55** [comment]
You have weapon in stash with added by mods attachment. Remove that weapon \ move to some container \ or use helper mod

No support for outdated versions
