### ISSUE TITLE
WHEN SELECTING THE SERVER FOLDER NO JSON FILES ARE PRESENT

### ISSUE THREAD

**Issue by noseihtam** [SkiTles55/SPT-AKI-Profile-Editor#119]
**Versions**
- SPT-AKI Server version
- SPT-AKI Profile Editor version
- List of installed mods

**Describe the bug**

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
[c06945745ec3efbadb7cfb7c.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/13032341/c06945745ec3efbadb7cfb7c.json)

**Comment by SkiTles55** [comment]
Absolutely unclear description, not filled properly bug report. Update, or it will be closed

**Comment by noseihtam** [comment]
how is it unclear? json files are not showing in the profile editor when selecting the correct path. All folder appear with no json files.

**Comment by SkiTles55** [comment]
Just select folder with your SPT-AKI Server, there no problems with that, all works
