### ISSUE TITLE
Money Not Always Added Properly

### ISSUE THREAD

**Issue by RogueTech67** [SkiTles55/SPT-AKI-Profile-Editor#12]
**Versions**
- SPT-AKI Server version - 2.2.2
- SPT-AKI Profile Editor version - 2.0
- List of installed mods - NONE

**Describe the bug**
I've been using this program for a few versions now. With each version, the ONLY issue I've consistently had is with adding money from the [Stash]. Yes I have a profile created. It NEVER adds the money the first or second time, and then after that it seems to randomly work. I've spent hours tryin to figure out what the "pattern" is for how to get it to work, or why it is failing. I'm at a loss. Is there a known issue with the money not always being adding to the profile correctly?

**Additional context**
SPT-AKI Profile file link

**Comment by SkiTles55** [comment]
@RogueTech67 bug report not completely filled. Profile file missed

**Comment by RogueTech67** [comment]
Hello sorry.  New to reporting things.  What is meant by "SPT-AKI Profile file link"?  Do you mean from/on the SPT-AKI site (i.e. https://www.sp-tarkov.com/) in which case I do not see where/how to create one.  If you mean the "downloads site" (i.e. https://hub.sp-tarkov.com/files/ ), then I have a userid/account/profile there (https://hub.sp-tarkov.com/user/12972-roguetech67/).  Sorry again.  I'll be happy to provide any info once I know what it is.  Thanks

**Comment by RogueTech67** [comment]
Maybe you mean this..... https://github.com/SkiTles55/SP-EFT-ProfileEditor/releases/tag/2.0

**Comment by SkiTles55** [comment]
@RogueTech67 I mean profile file from your server. It can be found on \user\profiles directory

**Comment by SkiTles55** [comment]
bug report not completely filled
