### ISSUE TITLE
Unable to add weapon Presets to Profile Editor via import. 

### ISSUE THREAD

**Issue by JunkoSpaceMommy** [SkiTles55/SPT-AKI-Profile-Editor#120]
My Version of SPT AKI is 3.7.0 My Version of SPT Profile Editor is 2.8.2 for SPT 3.7.0/.1
67 installed Mods
![2023-10-22_17-51-09](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/132549670/f98ad660-1468-4950-a6c8-51db373ca6b3)
![2023-10-22_17-51-32](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/132549670/b1ea9609-be95-4066-af41-08ad738610b9)
Screenshots of my mods list. This is easier than writing them all down and clogging space. 

The Bug is as follows: When I went to the presets tab in SPT Profile Editor, I saw that my fresh profile had no weapon builds or presets.
I then attempted from a separate folder where all my weapon presets are kept, ( I have them divided into vanilla and modded as to avoid conflicts with the editor) to enter them into the presets section as I have and was able to with the 3.5.8 version of SPT and that version of SPT Profile Editor. I got a message with the notification: "This file does not contain build" followed by the file path.

An example is provided below of the message. I am unsure as to why the presets do not import. I can guess why but they were able to be ported as of two versions ago and this was not an issue even across multiple versions in the past. (2.2 to 3.2.4 as an example)

![2023-10-22_17-33-49](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/132549670/551fc7c6-8e4e-4ab5-841c-757fa28fc893)

My Profile file is uploaded as a ZIP below. If you require more information pls let me know.

[e3aa715a23b4752a1d5cbaec.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/13064657/e3aa715a23b4752a1d5cbaec.zip)

**Comment by SkiTles55** [comment]
After changes in SPT-AKI 3.7.0, presets exported from older versions is incompatible. But you can update them, by open exported preset in good text editor, and adding field "type": "weapon". After changes preset file must look like:
```{
  "id": "4fcc7a8c299aa5179f2edf06",
  "name": "TestBuild",
  "root": "1926a17442c1c63c14641ba3",
  "items": [
    // items array
  ],
  "type": "weapon",
  "Parent": "5447b5f14bdc2d61278b4567"
}```
