### ISSUE TITLE
Копирование профиля

### ISSUE THREAD

**Issue by JavaRazrab** [SkiTles55/SPT-AKI-Profile-Editor#122]
Возможно, такая функция уже имеется, но я ее не смог найти.
Очень хотелось бы сохранять настройки Profile-Editor'a (PE) для последующей возможности применения их на какой-либо другой профиль. Это может послужить альтернативой копирования профиля, при, например, переносе на новую версию сервера. На данный момент, при копировании json'a с профилем, на новую версию сервера возможен ряд ошибок (особенно, если использовались моды). При помощи данной функции можно было бы создать новый профиль, скопировать все настройки с прошлого профиля (состояния квестов, инвентарь, торговцы и т.д.) и применить к только что созданному. Понятно, что перенести все не получится, и какая-то информация в любом случае будет утеряна, но это хоть что-то. Сейчас приходится открывать 2 окна PE, и вручную копировать состояния квестов и т.д. Это очень неудобно.

Прошу дать обратную связь, если на данный момент возможность скопировать состояние PE для дальнейшего его применение на другом профиле уже имеется.

**Comment by SkiTles55** [comment]
Такой функции сейчас нет. Много раз думал над возможными методами реализации, но пока что не подобрал подходящий.
