### ISSUE TITLE
I am handling your project on the SPT forum in China. According to the forum rules, I need your explicit authorization, so I hope you can authorize me

### ISSUE THREAD

**Issue by ghostLiulang** [SkiTles55/SPT-AKI-Profile-Editor#124]
Because I don't know your email address, I have to contact you here.
    Hello, I am handling your project on the SPT Chinese forum in China. As there is no Chinese translation for this project, many players in China are unable to use it conveniently. Therefore, I have added Chinese translation related code to the code and compiled it into a executable program that can be distributed in the forum.
I understand that the license type for this project is MIT, but based on the operating rules of the forum, I need your explicit authorization to allow me to move related finished products to the forum.
this link is the forum address ,in  this forum ,my nick is  "扎克的逃离塔克夫"
https://sns.oddba.cn/

this is talk with forum manager
<img width="744" alt="与管理人员的聊天截图" src="https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/25993397/100886d1-f3e6-40e3-8e64-2e5efc7a65e9">

thanks!

**Comment by SkiTles55** [comment]
There can't be explicit authorization, this open source project without limitations from license. And Chinese translation from one of users of oddba already integrated in project, and will be available in next release.
