### ISSUE TITLE
Error could not convert string 'AvailbleAfter' 

### ISSUE THREAD

**Issue by NoddyTech** [SkiTles55/SPT-AKI-Profile-Editor#128]
**Versions**
- SPT-AKI Server version 3.7.6
- SPT-AKI Profile Editor version 2.8.5
- List of installed mods

**Describe the bug**
I just got this error (see attached pic) today it was working fine yesterday and then I wiped my profile now I get this error
![Profile error](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/156909348/9db8ff84-408f-47bd-984c-c1a7b514fd69)

**Additional context**
SPT-AKI Profile file

[profile.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/13962478/profile.zip)

**Comment by NoddyTech** [comment]
O yes I did uninstall and reinstall, I don't want to mess with the code as I know nothing of coding

**Comment by NoddyTech** [comment]
Hi you can close this ticket as soon as I deleted the whole profile and started again it fixed itself

**Comment by SkiTles55** [comment]
fixed in fad1f0c540f8b4086833a7ad95560ee1860c9dd9
