### ISSUE TITLE
Bug report--fullProfile.userbuilds.weaponBuilds[buildld].Items is not iterable

### ISSUE THREAD

**Issue by torrestena** [SkiTles55/SPT-AKI-Profile-Editor#129]
**Versions**
- SPT-AKI Server version 3.8.0
- SPT-AKI Profile Editor version 2.8.6
- List of installed mods null

**Describe the bug**
After I use the editor and make some changes, such as mark one mission as "success". The game would stuck in the loading screen, and the sever would publish some red notice, see attached files.
When I create a new profile, it's ok to use the editor. But the issue mentioned above occurred after I play further with this profile.  
[For bug report.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14194246/For.bug.report.zip)

**Additional context**
SPT-AKI Profile file
[65be3d900005ac251dcf1c50.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14194217/65be3d900005ac251dcf1c50.zip)

Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

**Comment by SkiTles55** [comment]
there no support for BE builds

**Comment by torrestena** [comment]
Yes. Currently, in order to use the editor, I would delete all the weapon builds made by myself through the "preset--weapon(user)". And then everything will be fine.

**Comment by SkiTles55** [comment]
fixed in 0ca91c9bf39dcc79b5964c3e91267757436c5db6, test build for 3.8 be is available in discord
