### ISSUE TITLE
M9A3 9x19 17-round magazine not found

### ISSUE THREAD

**Issue by JoewAlabel** [SkiTles55/SPT-AKI-Profile-Editor#13]
Can you add the item M9A3 9x19 17-round magazine to add files, please?
I remember i can add all Beretta M9A3 in the past, but with new version 2.0 i can find only the pistol.
ty!!!!

**Comment by SkiTles55** [comment]
[FAQ: Some items are missing in the "Adding items" window](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/blob/master/ENGFAQ.md#some-items-are-missing-in-the-adding-items-window)
