### ISSUE TITLE
Errors in server (stuck at profile loading)

### ISSUE THREAD

**Issue by mhadi1385** [SkiTles55/SPT-AKI-Profile-Editor#133]
**Versions**
- SPT-AKI Server version : 3.8.0
- SPT-AKI Profile Editor version : Latest
- List of installed mods : nothing

**Describe the bug**
when i enter game from launcher it show just background (woods map i think)
without any button or text (just version of game and spt-aki)
in server show many Errors

**Comment by SkiTles55** [comment]
@mhadi1385  SPT-AKI Profile Editor version not specified, profile not attached, "in server show many Errors" - but no info about errors. Complete all needed info, or that issue will be closed

**Comment by SkiTles55** [comment]
incomplete bug report
