### ISSUE TITLE
".Items is not iterable" after adding item to stash using profile editor 

### ISSUE THREAD

**Issue by ItsBildo** [SkiTles55/SPT-AKI-Profile-Editor#135]
**Versions**
- SPT-AKI Server version - 3.8.0
- SPT-AKI Profile Editor version - 2.8.6
- List of installed mods - None

**Describe the bug**
After using the profile editor and saving changes, when you try to load into the game it freezes at the loading screen but the spinning circle continues. Red errors show up in the server log. From my understanding, it has to do with the ".Items" where I believe it needs to be ".items" (lowercase) but I am not a programmer so I could be wrong. It was just what I read in some of the other threads

**Additional context**
SPT-AKI Profile file - I have attached 2 versions; one before I added an item, and after:
https://drive.google.com/file/d/135dNQGSAgrFA1kMMh7K7tRtbV9I8nEKh/view?usp=drive_link

![SPT AKI Pr Ed errors](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/60265310/8df3c7f9-2ca2-451a-88aa-e110d4a54da5)

**Comment by SkiTles55** [comment]
Incompatible PE version. For 3.8.0 BE you should use test build from [discord](https://discord.gg/NTwSA4AfRP)
