### ISSUE TITLE
Stuck at profile loading (some errors in server)

### ISSUE THREAD

**Issue by mhadi1385** [SkiTles55/SPT-AKI-Profile-Editor#137]
**Versions**
- SPT-AKI Server version : 3.8.0
- SPT-AKI Profile Editor version : latest
- List of installed mods : nothing

**Describe the bug**

when i enter game from launcher it show just background (woods map i think)
without any button or text (just version of game and spt-aki)
in server show many Errors

**Additional context**

![Screenshot 2024-03-25 184632](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/84306642/e002c58a-9114-4711-b37e-ed2ecdf1a980)
![EscapeFromTarkov 3_25_2024 6_45_53 PM](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/84306642/93a9c2f3-0aa1-4a24-b0d1-f2ba9622d2d8)

**Comment by SkiTles55** [comment]
Firstly, learn to read and follow requirements, this is already second bug report that has not been filled completely
Secondly, for 3.8.0 BE you should use test build from [discord](https://discord.gg/NTwSA4AfRP)
