### ISSUE TITLE
Installation failure: "The feature you are trying to use is on a networkresource that is unavailable"

### ISSUE THREAD

**Issue by AtomStudioChina** [SkiTles55/SPT-AKI-Profile-Editor#138]
**Versions**
- SPT-AKI Profile Editor version: 2.8.6

**Describe the bug**
Installation failure
The feature you are trying to use is on a networkresource that is unavailable
The path C:\Users\***\Downloads\SPT-AKl ProfileEditor.InstaIIer.msi' cannot be found. Verify' that you haveaccess tO this location and try again, or try to find the......
![屏幕截图 2024-03-27 181402](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/91828989/763de1f1-c9b1-4a62-8ef2-18f1b70d90ff)
![屏幕截图 2024-03-27 181408](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/91828989/c98ec177-44f0-4052-a25e-f0702e85490c)
![屏幕截图 2024-03-27 181420](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/91828989/5c81e915-2471-429d-bb5c-c0d92992a9fc)
![屏幕截图 2024-03-27 181426](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/91828989/74be569b-e687-447d-a35c-73c312404181)
![屏幕截图 2024-03-27 181431](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/91828989/39b38c4b-b611-419e-b5f3-442dc4447afd)
![屏幕截图 2024-03-27 181436](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/91828989/e5e54494-856e-4353-b47a-295de91681fe)

**Comment by SkiTles55** [comment]
OS issue not related to PE\Installer
