### ISSUE TITLE
setup.exe not opening anything, same for SPT-AKI Profile Editor.Installer.msi

### ISSUE THREAD

**Issue by ReimuTheMiko** [SkiTles55/SPT-AKI-Profile-Editor#139]
**Versions**
- SPT-AKI Server version 3.7.6
- SPT-AKI Profile Editor version 2.8.6
- List of installed mods Boop Quest Zone API, Anastasia, PityLoot, SPTQuestingBots, Evelyn, Gilded Key Storage, Loot Value Backend, MoreCheckmarksBackend, Eyes Of A Trader, Ammostats, open-extracts, NoDiscardLimit, Svetlana, SWAG + DONUTS, Virtuals Custom Quest Loader, SAIN, DrakiaXYZ-Waypoints
- Windows 11 version 23H2 build 22631.3374

**Describe the bug**
After extracting the .zip into another file with nothing else in it, doubleclicking setup.exe (or right clicking and then clicking open) does not do anything, nothing opens including antivirus. Same also applies to the .msi. I tried using the 2.8.5 version, changing the destination folder name, moving destination folder into Singleplayer Tarkov root (not user > mods), but it still doesn't open anything. 

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

**Comment by ReimuTheMiko** [comment]
I was able to use the command prompt and run it via using "setup.exe" command, but it's still unable to run through windows explorer for some reason

**Comment by SkiTles55** [comment]
OS issue not related to PE\Installer
