### ISSUE TITLE
Fence Rep keeps resetting

### ISSUE THREAD

**Issue by Tombstonex** [SkiTles55/SPT-AKI-Profile-Editor#140]
**Versions**
- SPT-AKI Server version 3.8.0
- SPT-AKI Profile Editor version Newest Version
- List of installed mods
- aMoxoPixel-Painter
- BarlogM-Andern
- EpicRangeTime-Weapons
- ExpandedTaskText
- MoxoPixel-BlackCore
- MoxoPixel-MagTape
- MoxoPixel-TacticalGearComponent
- Skwizzy-NoDiscardLimit
- SWAG
- zSolarint-SAIN-SeverMod

**Describe the bug**
The Fence rep/Scav rep keeps resetting after i change it in profile editor. from max rep to fresh wipe rep
**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

**Comment by SkiTles55** [comment]
@Tombstonex  attach profile before and after editing, describe all your actions in PE, and when rep resetting happening

**Comment by acidphantasm** [comment]
[before - 660b319a00048c97e43853dc.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14910598/before.-.660b319a00048c97e43853dc.json)
[after - 660b319a00048c97e43853dc.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14910605/after.-.660b319a00048c97e43853dc.json)

I got this reported twice in the support channel of SPT and just figured out that PE is why it's happening

Profile editor is only writing the PMC data for Fence Rep - when you run as a scav on extract/death it'll overwrite the PMC fence rep as it no longer checks PMC fence rep for calculations in 3.8.0

If you run a PMC raid after setting it, the value will stay (and I believe writes to scav fence rep value, but a SPT dev can confirm)

**Comment by SkiTles55** [comment]
Fixed in e4033a01afbe2fe5b8b6d299d6fae365551bc25d, but this is not a critical issue, so there are no plans for the next release yet
