### ISSUE TITLE
Ошибка SPT-AKI Profile Editor

### ISSUE THREAD

**Issue by Dzhekin** [SkiTles55/SPT-AKI-Profile-Editor#141]
**Версии**          
- Версия SPT-AKI Server    3.7.6
- Версия SPT-AKI Profile Editor    2.9
- Список установленных модов   aCivicPainter, TacticalGearComponent, Game Panel HUD

**Опишите ошибку**
![Безымянный](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/165954351/cd913433-8786-469b-87d3-028b187bd875)

**Дополнительный контекст**
Файл профиля SPT-AKI
Просто создайте zip-архив с файлом вашего профиля и перетащите его сюда. Отчеты об ошибках без прикрепленного файла профиля будут закрыты без какой-либо помощи, если они связаны с профилем пользователя.
[aecffab8cf7efc1c94e2602f.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14858051/aecffab8cf7efc1c94e2602f.json)

**Comment by SkiTles55** [comment]
несовместимая версия сервера

**Comment by Dzhekin** [comment]
Откатил на старую версию Profile Editor, заработало)) Спасибо
