### ISSUE TITLE
Causes duplicate weapon/equipment builds in 3.8.0

### ISSUE THREAD

**Issue by DrakiaXYZ** [SkiTles55/SPT-AKI-Profile-Editor#142]
**Versions**
- SPT-AKI Server version: 3.8.0
- SPT-AKI Profile Editor version: Developer
- List of installed mods: None

**Describe the bug**
When editing anything in the profile, the `weaponBuilds` and `equipmentBuilds` arrays are re-written with their objects keys lowercased. This breaks SPT's lookup for updating builds, and results in duplicate builds being added to the profile. This then breaks the profile.

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

Before using PE:
[onGameStart-2024-04-05T175119657Z.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14889098/onGameStart-2024-04-05T175119657Z.json)

After using PE:
[660e4d2f0005c26a6da51c08.json](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14889099/660e4d2f0005c26a6da51c08.json)

Only change made using PE was to update the profile nickname

**Comment by SkiTles55** [comment]
fixed in 9058b2e872d6c6048f5683d24d0a7ed02991e252
