### ISSUE TITLE
[Suggestion]The modification of insurance

### ISSUE THREAD

**Issue by Levin-7** [SkiTles55/SPT-AKI-Profile-Editor#143]
**Describe the idea of new feature**
Hope There is a feature could edit the in progress insurance like the return time, retain time or something else.

**Comment by SkiTles55** [comment]
@Levin-7 This will be a very specific and little used feature. I don't have much time to develop the editor, so I can't devote time to it yet. However, if you or someone else studies the how insurance in the profile file works, provides test files and editing examples, perhaps this function will go into development
