### ISSUE TITLE
Error on Launch: "Could not convert string to integer: Custom. Path 'userbuilds.equipmentBuilds[0].buildType"

### ISSUE THREAD

**Issue by ValokAsura** [SkiTles55/SPT-AKI-Profile-Editor#144]
**Versions**
- SPT-AKI Server version: 3.8.0
- SPT-AKI Profile Editor version: 2.9.1 installed to "C:\Program Files\SPT-AKI Profile Editor\"
- List of installed mods: See screenshots below

**Describe the bug**
On launch, I receive the error: Could not convert string to integer: Custom. Path 'userbuilds.equipmentBuilds[0].buildType', line 41613, position 25. This prevents me from editing my profile.

**Additional context**
[Profile.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/14968370/Profile.zip)
Possibly related to: https://github.com/SkiTles55/SPT-AKI-Profile-Editor/issues/129
My guess is it's simply related to a mod adding custom entries to my profile that the program doesn't read, but I can't figure out what it would be. The Line and Position details don't line up with the Path it's describing as being line 41613. I looked at 'userbuilds.equipmentBuilds' but there is no data stored within it. "userbuilds.equipmentBuilds.BuildType doesn't seem to exist.

Thank you for your time! Feel free to let me know if I'm just being stupid =)

![Mods](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/40879862/24e189b1-fa8b-4594-a3fd-565143a6e705)
![BepInEx](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/40879862/40ed2e03-17ab-4395-b94a-09fd10967d68)
![BepInEx CWX](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/40879862/bad3e32b-0357-4b7f-9042-f6f4dbcd1486)
![Error Message](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/40879862/d805864b-735e-41a5-ab87-1ce70c12093b)

**Comment by SkiTles55** [comment]
@ValokAsura equipmentBuilds is empty, that error can't be shown in that profile. Make sure you set correct path for spt-aki server and select correct profile

**Comment by ValokAsura** [comment]
I apologize for my ignorance. It's resolved. After uninstalling the old version and installing the new, I assume there were still settings left behind that pointed to my old SPT directory, and thus, old profile. If the uninstallation removed the old settings, the error wouldn't have been encountered.

I thought the error was preventing the program from loading. Because I must have previously selected "Steel (Dark)" for the Color scheme, I never noticed (until today) that there was a settings button on the window border because the border and text color are fairly similar when I don't look at it because I Alt+F4 to close instead of clicking the "X."

Thank you for taking the time to review and respond! I'm embarrassed to say I never noticed the Settings button "hidden" in the border. "No matter how well you program an interface, a user will figure out a way to use it wrong."
