### ISSUE TITLE
Serious problem: After reading the archive. The archive will disappear

### ISSUE THREAD

**Issue by Dareto1st** [SkiTles55/SPT-AKI-Profile-Editor#146]
**Versions**
- SPT-AKI Server version 3.8.0
- SPT-AKI Profile Editor version 3.8.0
- List of installed mods none

**Describe the bug**
After reading the archive in modification tool . The archive will disappear.This caused my play progress to disappear and I wish I could modify it to not delete the save

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

**Comment by SkiTles55** [comment]
@Dareto1st I don't understand what you mean. PE can't remove profile. Try to make your bug report more clear.

**Comment by SkiTles55** [comment]
closed due to inactivity
