### ISSUE TITLE
Cannot add any healing item(Salewa, IFAK, Grizzly etc) to stash through profile editor (There is no healing item in the list)

### ISSUE THREAD

**Issue by Jacktherookie** [SkiTles55/SPT-AKI-Profile-Editor#147]
**Versions**
- SPT-AKI Server version 3.8.1
- SPT-AKI Profile Editor version 2.9.3
- List of installed mods

brightlaser
questingbots
livefleaprices
fpsunlocker
roublesforall
betterspawnplus
servervaluemodifier
nodiscardlimit
SAIN

**Describe the bug**
Cannot locate any first aid kit (IFAK, AFAK, Salewa etc) for adding item at stash
Although I can see in the list when I purchase in flea or merchant

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

[profiles.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/15282947/profiles.zip)

**Comment by SkiTles55** [comment]
https://github.com/SkiTles55/SPT-AKI-Profile-Editor/blob/master/ENGFAQ.md#some-items-are-missing-in-the-adding-items-window
