### ISSUE TITLE
Mod ProfileEditorHelper incompatible. It must execute at least one of IPostAkiLoadMod, IPostDBLoadMod, IPreAkiLoadMod

### ISSUE THREAD

**Issue by AtomStudioChina** [SkiTles55/SPT-AKI-Profile-Editor#150]
**Versions**
- SPT-AKI Server version: 3.8.3
- SPT-AKI Profile Editor version: 2.9.3
- ProfileEditorHelper

**Describe the bug**
Server reporting "Mod ProfileEditorHelper incompatible. It must execute at least one of IPostAkiLoadMod, IPostDBLoadMod, IPreAkiLoadMod"
The helper mod didn't work.

**Comment by SkiTles55** [comment]
@AtomStudioChina looks like you are lying about using versions, and trying use PE 2.9.4 test build in SPT-AKI 3.8.3, or PE 2.9.3 on SPT BE 3.9.0. That is incompatible pairs. Using PE 2.9.4 test build and PE 2.9.3 on one machine for diiferent server versions is also incompatible

**Comment by AtomStudioChina** [comment]
> @AtomStudioChina looks like you are lying about using versions, and trying use PE 2.9.4 test build in SPT-AKI 3.8.3, or PE 2.9.3 on SPT BE 3.9.0. That is incompatible pairs. Using PE 2.9.4 test build and PE 2.9.3 on one machine for diiferent server versions is also incompatible

So where can I get these pre-releases?

**Comment by SkiTles55** [comment]
> So where can I get these pre-releases?

PE test build in PE discord, SPT BE in SPT discord
Closed cuz provided data is incorrect
