### ISSUE TITLE
Filesize after saving the a newly edited profile can be concerning at a glance due to formatting

### ISSUE THREAD

**Issue by gopgop9000** [SkiTles55/SPT-AKI-Profile-Editor#151]
I wasn't sure to tag this as a bug or enhancement, so if I labelled it wrong let me know

**Versions**
- SPT-AKI Server version : 3.8.3
- SPT-AKI Profile Editor version : 2.9.3
- List of installed mods 
<details>
 <summary> Mods </summary>

-   SAIN 
-  Swag & Donuts  
-  BigBrain 
-  Waypoints 
-  MoreCheckmarks 
-  AmmoStats 
-  ServerValueModifier 1.8.2 
-  LootingBots 
-  Stash Search
-  Quest Zones
  AmandsGraphics 
-  Virtual's Custom Quest Loader
- Lotus (Trader)
- Scorpion (Trader)
- Artem (Trader)
</details>

**Describe the bug**
When saving the file, all tabs get replaced by 2 spaces, which increases the file size to a point that can seem suspicious at first.
When saving an edit to a profile, there were 148,196 lines, which grew to 148,228 lines, with a difference of 974,065 characters. This raised a red flag for me until I realized it was because it was formatted differently when saving.

**Additional context**
SPT-AKI Profile file
[tarkov.profiles.zip](https://github.com/user-attachments/files/15920002/tarkov.profiles.zip)

**Comment by SkiTles55** [comment]
fixed in e79f74b01a5ec59646ae32f14763bbbe36196203, but will be available only in next release for SPT 3.9.0
