### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Cantreallydoitman** [SkiTles55/SPT-AKI-Profile-Editor#158]
**Versions**
- SPT-AKI Server version 1.5.0
- SPT-AKI Profile Editor version 2.0
- List of installed mods WTT head voice selector, WTT WAAC

**Describe the bug**
When I try to save my changes, an error pops up saying "Object reference not set to an instance of an object," even if I didn't change anything

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
[profiles.zip](https://github.com/user-attachments/files/17612340/profiles.zip)

**Comment by SkiTles55** [comment]
no support for outdated versions
