### ISSUE TITLE
Не запускается через exe. При запуске исходников не видит сервер

### ISSUE THREAD

**Issue by nickalps** [SkiTles55/SPT-AKI-Profile-Editor#16]
**Версии**
- Версия SPT-AKI Server - 2.3.0
- Версия SPT-AKI Profile Editor - 2.1
- Без модов

**Ошибка 1**
При запуске exe скачанного с https://github.com/SkiTles55/SPT-AKI-Profile-Editor/releases/tag/2.1
Ничего не происходит. На секунду в диспетчере появляется процесс  SPT-AKI Profile Editor и пропадает.

**Ошибка 2**
При скачивании исходников и запуске проекта в VS2022
Открывается окно, если выбрать каталог сервера - пишет "Сервер SPT-AKI не найден. Попробовать снова?" У редактора версии 2.1 заявлена поддержка сервера 2.3.0, но сервер не находит D:

**Comment by SkiTles55** [comment]
@nickalps 
Запускается в Visual Studio - соответственно проблема в твоей системе. Установи .NET 6, проверь что антивирус не блокирует запуск программы
Не находит сервер - Выбираешь папку не с сервером \ в папке сервера отсутствуют требуемые файлы. Для начала запусти сервер, создай профиль и зайди в игру.

**Comment by Tsubasumi** [comment]
@SkiTles55 "Сервер SPT-AKI не найден. Попробовать снова?" так же пишет, но я уже перебрал все файлы в его поисках. Профиль есть и я на нём играл, но ничего не получается :с

**Comment by SkiTles55** [comment]
@Tsubasumi покажи содержимое файла AppSettings.json из папки с редактором. Можешь просто прикрепить его сюда

**Comment by Tsubasumi** [comment]
@SkiTles55
[AppSettings.txt](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/8454388/AppSettings.txt)
На .txt поменял перед загрузкой сюда*

**Comment by SkiTles55** [comment]
@Tsubasumi никаких проблем нет. Сервер выбирается, все прекрасно работает. Значит ты выбираешь не правильную папку
