### ISSUE TITLE
Unable to edit profile

### ISSUE THREAD

**Issue by cryptotabluvox** [SkiTles55/SPT-AKI-Profile-Editor#17]
**Versions**
- SPT-AKI Server version - 2.3.1
- SPT-AKI Profile Editor version - 2.1.1
- List of installed mods -
 KMC SVM, Back To 12.11!

**Describe the bug**
When I tried to run the editor, it throws me an error. It says, something that marked as failed. I'm guessing that's the quest that has been marked as failed. The quest that involved Prapor, Therapist and Skier. When, I tried create a new profile and edits it, no errors occured. Not sure why only this throws me an error. Before that quest, I have issues editing the profile.

**Additional context**
SPT-AKI Profile and error images as attached.
[3aabedcdece6b7093c76d410.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/8492850/3aabedcdece6b7093c76d410.zip)
![Screenshot (12)](https://user-images.githubusercontent.com/89818045/163493413-dd27815e-8211-4b86-85f6-a8a5f2d7d404.png)

**Comment by SkiTles55** [comment]
@cryptotabluvox  I didnt see this quest status value before. Will be fixed in next versions. For temporary solution you can open profile in Notepad++, find and change "MarkedAsFailed" value to any other (Locked, AvailableForStart, Started, Fail, AvailableForFinish, Success)

**Comment by SkiTles55** [comment]
Fixed in 0622e94fdf7e0b73a3f9400ca43f8b4824e9feef
