### ISSUE TITLE
Stash - Adding Items - SEARCH Broken in SPT-AKI Profile Editor Version 2.2

### ISSUE THREAD

**Issue by RogueTech67** [SkiTles55/SPT-AKI-Profile-Editor#23]
**Versions**
- SPT-AKI Server version: 2.3.1
- SPT-AKI Profile Editor version: 2.2
- List of installed mods: NONE

**Describe the bug**
With the creation of new "setup install" version 2.2, "searching" in Stash - Adding Items is NOT working.  If you type in say "devil" it is now showing the entire "tree" in which the item is under.  So it Shows [Provisions] - and ALL the items under [Drinks] and [Food].  Very obvious to see.   Thanks

**Additional context**
SPT-AKI Profile file link

**Comment by SkiTles55** [comment]
Yes, I know about this problem, but unfortunately I found out about it after sending the update. Fixed in 202bfe39cac524d91ab9cd247e03ce680276ab14
