### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by ShadowGhost31** [SkiTles55/SPT-AKI-Profile-Editor#33]
**Версии**
- Версия АКИ 3.0.0
- Версия едитора 2.3
- Модов: 0

**Опишите ошибку**
Профиль не грузит...
При нажатии на закрыть :
![image](https://user-images.githubusercontent.com/108402389/176418259-ed29f2de-d34d-4089-a029-86b332137ab7.png)
![image](https://user-images.githubusercontent.com/108402389/176418175-9b3d9357-83fa-4732-b8e0-0f86e0a3c614.png)
Позже не грузит : 
![image](https://user-images.githubusercontent.com/108402389/176418473-60a2b979-fe13-4331-ae48-4be30209424c.png)

**Дополнительный контекст**
![image](https://user-images.githubusercontent.com/108402389/176418259-ed29f2de-d34d-4089-a029-86b332137ab7.png)

**Comment by SkiTles55** [comment]
Исправлено в https://github.com/SkiTles55/SPT-AKI-Profile-Editor/commit/1c15237b61477aa7e3c47c333cf20cfef8dd832b, скоро будет обновление. Пока что можно найти в профиле статус "Expired" и поменять на любой другой

**Comment by SkiTles55** [comment]
Да, в самом файле профиля. Открываешь его в notepad++, и на строчке 29633 меняешь "Expired" на "Fail"
