### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sabaadmin** [SkiTles55/SPT-AKI-Profile-Editor#40]
**Versions**
- SPT-AKI Server version : 3.2.3
- SPT-AKI Profile Editor version : 2.4.2
- List of installed mods : BLUEHEAD'S AIO TRADER 2.0.4
- OS : Windows11

**Describe the bug**
I get a mysterious error

![1](https://user-images.githubusercontent.com/94890302/190383591-f7b12acb-b0c0-4677-aa38-f52bc3e5e6eb.png)
![2](https://user-images.githubusercontent.com/94890302/190383608-fc7aa48e-b132-41d5-8fc0-ee01afbe9d4c.png)

**Comment by SukiTibi** [comment]
I have the same issue.

**Comment by sabaadmin** [comment]
I was able to solve it myself.
Probably it's due to SPT-AKI's new mode.

**Comment by sabaadmin** [comment]
A new mode is an edition

**Comment by SkiTles55** [comment]
Bug report incomplete
