### ISSUE TITLE
Краш приложения при любом действии

### ISSUE THREAD

**Issue by SineD26** [SkiTles55/SPT-AKI-Profile-Editor#47]
**Версии**
- Версия SPT-AKI Server 3.3.0
- Версия SPT-AKI Profile Editor 2.4.2
- Список установленных модов: нет модов

**Опишите ошибку**
Четкое и краткое описание ошибки.
Установил, все указал, на версии спт аки 2.2.3 все работает хорошо, любые 3.х.х версии выдают такую ошибку после любого действия и нажатия "сохранить". Пробовал переустанавливать SPT-AKI Profile Editor и чинить NET 6.0, не помогло.
На скринах указаны две последовательные ошибки (после ОК появляется второе окно)

**Дополнительный контекст**
Ссылка на файл профиля SPT-AKI: G:\EscapeFromTarkov_0.12.12.32.20243_SPT-AKI_3.3.0\EscapeFromTarkov\user\profiles\770eb07f147cbf54d81858db.json
![1](https://user-images.githubusercontent.com/119014933/203868659-8855af0e-3f74-4fdb-870f-d49ca7eb479d.jpeg)
![2](https://user-images.githubusercontent.com/119014933/203868660-08deefd4-612c-4600-aa54-01f98cf71b81.jpeg)

**Comment by SkiTles55** [comment]
@SineD26 Локальная ссылка на файл профиля это конечно сильно... Но нужен прикрепленный сюда файл профиля, что бы я мог его скачать, и посмотреть что именно в нем вызывает ошибку.

**Comment by SineD26** [comment]
@SkiTles55 Я обычный  юзверь, не судите строго, пожалуйста)
Прикладываю разные профили, везде одинаковое поведение (всё читается корректно программой, но при сохранении изменений появляется такая ошибка, даже в стоковых профилях), версии spt aki 3.2.5 и 3.3.0: https://github.com/SineD26/tarkov-profile
https://github.com/SineD26/tarkov-profile/blob/e4ad07451820fd8dd3e9cd6486419d32a9379cda/11a6290ffa7458c0d22cccd2.json

надеюсь правильно сделал

**Comment by SkiTles55** [comment]
@SineD26 У тебя в профиле у скупщика 4-й уровень лояльности, хотя их всего 2. Поставь 2-й уровень перед сохранением и ошибка должна уйти
