### ISSUE TITLE
Editor 2.5 for SPT-AKI 3.4.0/3.4.1 Causes Issues Adding Stash Items

### ISSUE THREAD

**Issue by RogueTech67** [SkiTles55/SPT-AKI-Profile-Editor#53]
**Versions**
- SPT-AKI Server version - 3.4.0 / 3.4.1
- SPT-AKI Profile Editor version - 2.5
- List of installed mods - NONE

**Describe the bug**
Install clean game version ( 0.12.12.32.20765 ) with either SPT-AKI 3.4.0 or 3.4.1.  Run first time creating User1 - Edge of Darkness, launch the game, choose most defaults (USEC), and check the stash and verify it looks like it always does (and it does).  Exit the game.  (Optional - Save off the \user profile directory to run multiple tests).  Install Profile Editor 2.5 to C:\NoScan\Games\SPT-AKI Profile Editor.  Verify any existing copy of the app' working/save folder (i.e. C:\Users\Steel\AppData\Roaming\SPT-AKI Profile Editor) is NOT there, so it is created clean.  Run the profile Editor.  Add any item to the stash (i.e. Gingy Key Chain) and save the profile.  Launch the game.
ISSUE:  It will add the item to a slot in the existing stash.  In this case, it always chooses the first [HK MP5 9x19PARA] in the top left part of the Stash.  If you add a third single cell item, it will overwrite the second existing [HK MP5 9x19PARA] in the top right. 
    This started with the creation of PE 2.5.  The issue was not in the previous 2.4.2 version for game version ( 0.12.12.32.20243 ) with SPT-AKI 3.3.0, or any of the past few AKI versions, (i.e. 3.2.5, 3.2.4,...).  I see there were specific changes made for 2.5 to address issues with "Error while adding a item".  Seems a little coincidental.  I ran this test clean on 2 separate laptops with 2.5 and 3.4.0/3.4.1, and got the exact same results every time.  I can not see how every user (of at least the Edge of Darkness version) is not seeing this.  Thanks in advance for your time in looking in to this, and the effort you put in to maintaining it.   I love this Editor, and it's the first thing I try with every new SPT-AKI release.
************************************************************

Did some more testing, and after about 30 minutes, the "pattern" of the issue became immedately apparent.  Add 1x1 items one or two at a time and check the stash.  Starting from the top left, it is filling in "overtop" of each and every "rifle", not the hand guns.  It does not replace/reuse all the 1x1 cells, but only some of them for each rifle.  It does this until it gets to the bottom, then it seems to be normal.  But then, still using the Editor, start deleting the items a few at a time in reverse order, an you will see the rifle(s) it had seemingly replaced reappear back in the stash.  If you delete each and every itme in reverse order, you will get your original stash back.
    This definately seems to have something to do with this specific change/fix you made, "Removed item size calculation if it is not a weapon" - [ https://github.com/SkiTles55/SPT-AKI-Profile-Editor/issues/44 ].  This also seems a lot like the issue I reported, "First Added Stash Items Not Appearing For Game Editions With Default "Rotated" Stash Items" - [ https://github.com/SkiTles55/SPT-AKI-Profile-Editor/issues/18 ] back On May 1, 2022 where you found the issue and fixed it.  Hope this info helps in your finding a solution. Thanks again

https://github.com/SkiTles55/SPT-AKI-Profile-Editor/issues/44

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
[user-EoD-3.4.0.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10438653/user-EoD-3.4.0.zip)

**Comment by FR0Z3** [comment]
Adding money seems also replacing existing weapons in the stash?

**Comment by SkiTles55** [comment]
Fixed in fe0da300a12cb6ee36235c3d7d98d2588c1035da

**Comment by RogueTech67** [comment]
Thanks SkiTles55.  Any timeframe for when the new version will be released with the fix in it?
