### ISSUE TITLE
Adding money through editor seems replacing any weapons, and the adding items menu does not have anything in it.

### ISSUE THREAD

**Issue by FR0Z3** [SkiTles55/SPT-AKI-Profile-Editor#55]
**Versions**
- SPT-AKI Server version: 3.2.5(19904)
- SPT-AKI Profile Editor version 2.5
- List of installed mods:
BepInEx Mods:
kmyuhkyuk-GamePanelHUD
kmyuhkyuk-GrenadeSprite
CWX-MasterKey
Faupi-MunitionsExpert
whF.ClientModLoader

Mods installed in ClientMods:
Dynamic In-game Maps

Other Mods:(These are basiclly custom weapons with custom attachments)
tkf-SuperMods(required for some independant custom-painted guns, and these non-listed custom weapons cannot be listed here since you will need a 3rd party forums account to use.)
Mass_V308
KerryRoss_MK47
zAT-aris

**Describe the bug**
The Replacing Problem: After adding some money through the editor(sry I forgot to backup the save file for comparison, but the lost guns are no big deals.), starting the game found out some of the items was replaced by the rubles I added through the editor. Some of the items got replaced were insured, and some are not. The items got replaces are basiclly weapon related. I think I remember some of the not insured guns also got replaced with rubles. weird enough huh? A after edited profile will be attached.

The Nothing in the adding items section: I think after updating to V2.5 causing the adding items section gone blank and most of the localized stuff was turned into IDs. I will attach the screenshot for this. Also the Merchants, Quests, Hideout, Weapon Mastering, Clothing section also got effected.

**Additional context**
Screenshots:
![adding_items](https://user-images.githubusercontent.com/33184021/213793427-0d85e96a-0d6c-45a2-bb5e-f4c9d9b46321.jpg)
![merchants](https://user-images.githubusercontent.com/33184021/213793437-239eb5ac-32e3-4107-8458-3d1f3cf798e7.jpg)

SPT-Aki Profile: [Profile_Without_any_mod_items_in_stash.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10469746/Profile_Without_any_mod_items_in_stash.zip)

**Comment by SkiTles55** [comment]
SPT-AKI Profile Editor 2.5 incompatible with SPT-AKI 3.2.5
