### ISSUE TITLE
добавление предметов не работает

### ISSUE THREAD

**Issue by proma462346** [SkiTles55/SPT-AKI-Profile-Editor#57]
**Версии**
- Версия SPT-AKI Server 2 2 3 7
- Версия SPT-AKI Profile Editor последняя
- Список установленных модов
нету
**Опишите ошибку**
Четкое и краткое описание ошибки.
не могу добавить предмет (там просто пусто)
**Дополнительный контекст**
Файл профиля SPT-AKI (не требуетца для решения проблеми)
Просто создайте zip-архив с файлом вашего профиля и перетащите его сюда. Отчеты об ошибках без прикрепленного файла профиля будут закрыты без какой-либо помощи, если они связаны с профилем пользователя.
(и еще если не сложно как бистро реролить товар у торговцов?)

**Comment by SkiTles55** [comment]
Несовместимая версия сервера

**Comment by proma462346** [comment]
для 2 2 3 7 какая версия нужна editorа?
