### ISSUE TITLE
ошибка при установке 

### ISSUE THREAD

**Issue by proma462346** [SkiTles55/SPT-AKI-Profile-Editor#58]
![Знімок екрана 2023-01-31 202933](https://user-images.githubusercontent.com/87522287/215852681-ee17cc42-f19b-49b3-a40f-2751bf6b14a7.jpg)
![Знімок екрана 2023-01-31 202917](https://user-images.githubusercontent.com/87522287/215852696-07b2ed4a-0ef0-4674-b45f-77e910e5be16.jpg)
я уже пробовал удалят старие версии не помогло

**Comment by SkiTles55** [comment]
Ошибка винды, ни как не связано с проектом

**Comment by proma462346** [comment]
![изображение](https://user-images.githubusercontent.com/87522287/216053277-b024885f-54d3-4a6b-b9bf-492e89564158.png)
с етим што делать?
