### ISSUE TITLE
Error fix about the decimal type of life value in the archive

### ISSUE THREAD

**Issue by ghostLiulang** [SkiTles55/SPT-AKI-Profile-Editor#60]
**Versions**
- SPT-AKI Server version 3.4.0
- SPT-AKI Profile Editor version
- List of installed mods
none
**Describe the bug**
in SPT-AKI Profile Editor\Core\ProfileClasses\CharacterHealth.cs this file health vailue  type need is floot or double , dosn't is int
Because in the spt-aki profile , life value is of decimal type

**Additional context**

**Comment by ghostLiulang** [comment]
[fe4432757ec0b740f5456b5a.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10575880/fe4432757ec0b740f5456b5a.zip)

**Comment by SkiTles55** [comment]
Fixed in c027f4aadbe16bff26b9357dac58cc57ac0d3c2d
