### ISSUE TITLE
ISSUE Adding Global Items Presets in Editor 2.5

### ISSUE THREAD

**Issue by RogueTech67** [SkiTles55/SPT-AKI-Profile-Editor#61]
**2.5**
- SPT-AKI Server version - 3.4.1
- SPT-AKI Profile Editor version - 2.5
- List of installed mods - NONE

**Describe the bug**
MAY be part of this existing reported issue that you said you have identified and fixed and will be in the next release.  Again, the pattern of what is happening and what is being "overwritten" is pretty easy to see.   Thanks.
- https://github.com/SkiTles55/SPT-AKI-Profile-Editor/issues/53
- 
Steps:
- Clean user EOD Profile to start
- Clear/Discard Items in top 20 or so rows of the EOD stash (Exit)
- *** #-# indicates items starting slots/square in the stash
- Add first one in each 3 Weapons categories
	- Simonov SKS (Horizontal 1-1)
	- 3 empty spaces (should be AK-74N)
	- VSS Vintorez (Vertical - 1-9)
	*** Observation - the VSS went "vertical" into the would be AK-74N's horizontal slots making it "disappear"???
- Next add first 4 Assault rifles (i.e 4 AK's)
	- AK-74N (Horizontal 2-1) other 3 did not show
	- AKS-74U (*** MISSING/ NOT SHOWING)
	- AKS-74UB (*** MISSING/ NOT SHOWING)
	- AKS-74UN (*** MISSING/ NOT SHOWING)
- Next add Gingy Keychain
	- Gingy went into slot 1-10 (VSS Vintorez DISAPPEARED)
	- AKS-74UB (APPEARED Vertical in slot 2-8)
- Next delete Gingy Keychain
	- VSS Vintorez (Vertical - 1-9) (REAPPEARED)

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
[user.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10678209/user.zip)

**Comment by SkiTles55** [comment]
Looks like that resolved in https://github.com/SkiTles55/SPT-AKI-Profile-Editor/issues/53
