### ISSUE TITLE
Can Not Sell Added Stash Items to Traders

### ISSUE THREAD

**Issue by RogueTech67** [SkiTles55/SPT-AKI-Profile-Editor#62]
**Versions**
- SPT-AKI Server version - 3.4.0 / 3.4.1 / 3.5.0 BE
- SPT-AKI Profile Editor version - 2.5
- List of installed mods - NONE

**Describe the bug**
Added (1) Item from each of the 12 main categories in the [Stash] -> Adding items].  When going to Traders -> Sell, the items show as "green" when dragged over to the Sell section, but can NOT be added for sale.  Some were "FIR" and others not, it did not matter.  If this is by design, I apologize.  If not, then there appears to be an issue.   Thanks in advance.

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile
[user-341.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10714021/user-341.zip)

**Comment by SkiTles55** [comment]
Old known bug, without solution for now. This issue not critical, maybe will be resolved in the future, but with low priority
