### ISSUE TITLE
Can't add certain Medical Items

### ISSUE THREAD

**Issue by GrooveTorped** [SkiTles55/SPT-AKI-Profile-Editor#63]
**Versions**
- SPT-AKI Server version: 3.5.0
- SPT-AKI Profile Editor version: 2.6
- List of installed mods: NONE

**Describe the bug**
When I use the 2.6 version of the profile editor for SPT-AKI 3.5.0 I am unable to add medical items such as the Grizzly Medical Kit, Salewa and CAR kit to my stash. The profile editor finds no items with said names.

**Additional context**
SPT-AKI Profile file: [SPT-AKI 3.5.0 User Profile.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10743153/SPT-AKI.3.5.0.User.Profile.zip)

**Comment by SkiTles55** [comment]
https://github.com/SkiTles55/SPT-AKI-Profile-Editor/blob/master/ENGFAQ.md#some-items-are-missing-in-the-adding-items-window
