### ISSUE TITLE
exporting preset bug

### ISSUE THREAD

**Issue by cheese8584** [SkiTles55/SPT-AKI-Profile-Editor#64]
**Versions**
- SPT-AKI Server version: 3.5.0
- SPT-AKI Profile Editor version: 2.6.0

When adding a preset weapon to my inventory from the profile editor I cant scope in with any gun ingame

edit: this happened after adding a few guns at once and after loading into raid some pistol iron sights were able to scope in

**Comment by SkiTles55** [comment]
@cheese8584 please fill bug report completely, or this will be closed
