### ISSUE TITLE
В профиле нет файла

### ISSUE THREAD

**Issue by 2222fds** [SkiTles55/SPT-AKI-Profile-Editor#65]
**Versions**
- SPT-AKI Server version 3.5.0
- SPT-AKI Profile Editor version 3.5.0
- List of installed mods
3.3.0
**Describe the bug**
Файл профиля не существует, когда вы пытаетесь выбрать его

**Additional context**
SPT-AKI Profile file
Just create zip archive with your profile file and drag'n'drop here. Bug reports without attached profile file will be closed without any help if they related to user profile

[profiles.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10805951/profiles.zip)

**Comment by SkiTles55** [comment]
Никаких проблем с профилем нет, и он открывается в редакторе без проблем. @2222fds в чем именно проблема?

**Comment by SkiTles55** [comment]
Недостаточно данных
