### ISSUE TITLE
Репутация барахолки

### ISSUE THREAD

**Issue by DuMoH4uK35** [SkiTles55/SPT-AKI-Profile-Editor#67]
Дмитрий, здравствуйте.
Версия SPT-Aki Server - 3.5.0
Версия Profile Editor - 2.6

Ошибка:
При сохранении профиля в Editor, репутация барахолки сбрасывается на 0.00 и не поднимается выше. Откат помог вернуть значение которые было до сохранения профиля - 0.46 но, репутация так же оставалась на одном уровне( при продаже предметов на барахолке, репутация не поднималась, хотя горела синяя стрелочка вверх).

Файл профиля:
[01bc053e9d24500f33fafd6e.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10812246/01bc053e9d24500f33fafd6e.zip)

**Comment by SkiTles55** [comment]
Исправлено в 1a544ae339c0c7457f15ddce8116b1a04128e992

**Comment by DuMoH4uK35** [comment]
> Исправлено в [1a544ae](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/commit/1a544ae339c0c7457f15ddce8116b1a04128e992)

Спасибо)
