### ISSUE TITLE
Vendors not accepting items created by the profile editor

### ISSUE THREAD

**Issue by havaed** [SkiTles55/SPT-AKI-Profile-Editor#69]
**Versions**
- SPT-AKI Server version - 3.5.0
- SPT-AKI Profile Editor version - 2.6

**Describe the bug**
Trying to sell to a vendor a item created using the profile editor results in negative from the vendor. 
I played around with the profile file and noticed that the items created had non-hexadecimal characters. Somehow the game doesn't care about it, but the vendor notice it because once the invalid chars were replaced in the IDs, the items could the sold perfectly.

**Additional context**
[profile.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10829055/profile.zip)

**Comment by havaed** [comment]
I've created a PR with a fix
https://github.com/SkiTles55/SPT-AKI-Profile-Editor/pull/68

**Comment by SkiTles55** [comment]
@havaed Good job. Thank you!
