### ISSUE TITLE
The given key [item] was not found in the dictionary

### ISSUE THREAD

**Issue by vinniehat** [SkiTles55/SPT-AKI-Profile-Editor#70]
**Versions**
- SPT-AKI Server version 3.5.0
- SPT-AKI Profile Editor version 2.6.1
- List of installed mods
-- ArmaLite Reloaded (Trader)
-- BetterKeys
-- Faupi Munitions Expert
-- Gunsmith Reboot
-- Hideout Architect
-- JoshMate's Better Backpacks
-- **Kawaii Weapons Mod** <-- Presumably what the items are from that are throwing the error
-- KcY SeeItemValue (Outdated, gotta remove it)
-- ExamineAllItems
-- CustomCameraRecoil
-- MICC
-- EOTech Overhaul
-- SBNV
-- SPT-Realism-Mod
-- SWAG
-- PathToTarkov
-- Valen's Progression
-- ZeroTimes

**Describe the bug**
When editing anything that has to do with my stash, I receive an error about a key not being in the dictionary. It changes depending on what I am trying to do, but this is the specific item error for when I try to add rubles to my stash.
When I try to add a preset to my stash, I get the same error just with a different item. This happens regardless of whether or not I am adding an item that has a component of the KWM mod or not.
![image](https://user-images.githubusercontent.com/13600763/221454188-317af96c-d3f6-402a-b9b7-2cfe4d97d08b.png)

**Additional context**
SPT-AKI Profile file
[f6f3d95e40dd94c57b0229b4.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10835465/f6f3d95e40dd94c57b0229b4.zip)

Please let me know if I can help you in any way! Logs, etc! Thank you :D

**Comment by SkiTles55** [comment]
@vinniehat Your stash contains weapon (Colt M45A1 .45) builded with modded item. Application can't calculate weapon size in this case, and in result, can't get count of free slots in stash. This can't be fixed, no way to access modded items parameters. 

What you can do for avoid this error:

- Remove this item, and do not put other weapons with modded items (or other modded items) in root of stash, keep them in containers, and you will be abble to add items via profile editor
- In game, move this weapon to container, as it described above
- You still can add items in to other containers in stash, if they not have modded items
