### ISSUE TITLE
Unable to increase Flea Market Standing

### ISSUE THREAD

**Issue by AAR0705** [SkiTles55/SPT-AKI-Profile-Editor#75]
**Versions**
- SPT-AKI Server version: 3.5.3
- SPT-AKI Profile Editor version: 2.6.1
- List of installed mods: None

**Describe the bug**
I am unable to increase the standing with ragfair. I can up the number but upon clicking Save Profile, it does not save, and reverts back to 0.2. This does not happen with the other traders. I have also tried this on a completely fresh profile, same issue. If you could tell me how I can manually edit it i'm happy to do so.

**Additional context**
SPT-AKI Profile file: 
[8966f3b48bb79cc5a8c2c218.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/10991924/8966f3b48bb79cc5a8c2c218.zip)

**Comment by SkiTles55** [comment]
Manual path is "characters" - "pmc" - "RagfairInfo" - "rating"

**Comment by SkiTles55** [comment]
Fixed in 70ec49c
