### ISSUE TITLE
Некорректная работа с "аварийной стеной" в убежище

### ISSUE THREAD

**Issue by Krinkelss** [SkiTles55/SPT-AKI-Profile-Editor#77]
**Версии**
- Версия SPT-AKI Server - 3.5.3
- Версия SPT-AKI Profile Editor - 2,6,1
- Список установленных модов: PreyToLive-BetterSpawnsPlus

**Опишите ошибку**
Некорректное отображение уровня "Аварийной стены", от трёх и выше всегда показывается 3. И при сохранении, если уровень >3 то откатывается до 3. По этому при работе с профилем через программу "аварийная стена" всегда полуразобрана

**Дополнительный контекст**
Во вложении файл профиля, уровень "аварийной стены" шестой, но программа упорно показывает третий.
[719e2d8bb2bbc48dcd6020e3.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/11002133/719e2d8bb2bbc48dcd6020e3.zip)

**Comment by SkiTles55** [comment]
Исправлено в  93e7e14
