### ISSUE TITLE
Не снимаются галочки на вкладке "Одежда"

### ISSUE THREAD

**Issue by Krinkelss** [SkiTles55/SPT-AKI-Profile-Editor#78]
**Версии**
- Версия SPT-AKI Server - 3.5.4
- Версия SPT-AKI Profile Editor - 2.6.2
- Список установленных модов - "PreyToLive-BetterSpawnsPlus"

**Опишите ошибку**
Вкладка "Одежда". Сначала поставил все галочки, нажал сохранить, закрыл программу. Через пару дней решил всё одежду заблокировать. Открыл программу, снимаю галочки. Но стоит прокрутить список вниз, а потом вернуться наверх и галочки становятся вновь отмеченными. При этом если несколько раз прокрутить список вверх вниз то некоторые галочки, в произвольном порядке, то становятся снятыми то вновь отмеченными

**Дополнительный контекст**
Файл профиля SPT-AKI
[e4526e40c480d201344e3e69.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/11088030/e4526e40c480d201344e3e69.zip)

**Comment by Krinkelss** [comment]
Маленькое дополнение. Снимаем несколько галочек, без прокрутки списка, нажимаем "Сохранить" и эти галочки становятся отмеченными

**Comment by SkiTles55** [comment]
Исправлено в b96b5a954fdd654b7f53e26ea7273fb4a0019cae
