### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by BoxshiSL** [SkiTles55/SPT-AKI-Profile-Editor#79]
**Версии**
SPT-AKI Server 3.5.4
SPT-AKI Profile Editor 2.6.3

При установке выдает ошибку 2755, либо то, что на скрине
Не знаю это ошибка моей системы, или с вашей стороны, но я прошу помощи
![image](https://user-images.githubusercontent.com/104085372/230685715-403f2e24-a8bd-4f69-b33b-d8469cd1afb3.png)

**Comment by SkiTles55** [comment]
ошибка системы
