### ISSUE TITLE
Некорректная работа со статусом квеста

### ISSUE THREAD

**Issue by Krinkelss** [SkiTles55/SPT-AKI-Profile-Editor#83]
**Версии**
- Версия SPT-AKI Server - [3.5.6 (23043)]
- Версия SPT-AKI Profile Editor - 2,6,3
- Список установленных модов - dvize.BushNoESP + SAIN

**Опишите ошибку**
Квест Егеря: Путь выживальщика - Живчик. Задаю статус AvailableForFinish и нажимаю кнопку сохранить, при этом вылазит сообщение о совершенно других квестах:
![Снимок экрана 2023-05-18 084021](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/assets/8791598/64d59de0-1041-4f2c-93c8-6652cd3fa504)

**Дополнительный контекст**
Файл профиля SPT-AKI
Просто создайте zip-архив с файлом вашего профиля и перетащите его сюда. Отчеты об ошибках без прикрепленного файла профиля будут закрыты без какой-либо помощи, если они связаны с профилем пользователя.
[1979a7cbeab0538ae2d140ad.zip](https://github.com/SkiTles55/SPT-AKI-Profile-Editor/files/11504724/1979a7cbeab0538ae2d140ad.zip)

**Comment by SkiTles55** [comment]
Все работает корректно. Если проверка квестов не требуется, можно установить в настройках "Действие по умолчанию для проблем с профилем" - "Всегда игнорировать"

**Comment by Krinkelss** [comment]
Тады пардон за беспокойство
