### ISSUE TITLE
Create a standalone portable version of the application

### ISSUE THREAD

**Issue by ScrewTSW** [SkiTles55/SPT-AKI-Profile-Editor#92]
**Describe the idea of new feature**

It would be nice to have a standalone application that does not require an installer (why is that the case? I'd like to understand that)

Also an improvement could be to migrate to .NET Core 3.1+ instead of using .NET 6
This would allow you to completely self-contain the executable and it's dependencies
See reference: https://stackoverflow.com/a/66003931
This would drop the requirement for a runtime

**Additional context**

**Comment by SkiTles55** [comment]
Sorry, but not. If you realy needed it, you can download project and compile for portable use. Also downgrading .NET not needed, .NET 6 is newer then .NET Core 3.1, and also contains ability for create self-sontained apps, but size of this apps are incredible big (not matter .NET Core 3.1 or .NET 6).

**Comment by astradamus** [comment]
Just letting you know that a sizeable portion of people are not going to use a software like this that requires installation (myself included).

It is an unusual and inappropriate ask for this sort of software.
