### ISSUE TITLE
Копирование название предметов

### ISSUE THREAD

**Issue by Krinkelss** [SkiTles55/SPT-AKI-Profile-Editor#96]
**Опишите идею новой функции**
Доброго времени суток. Добавьте возможность копирование название предметов в разделе "Сборки". А то оружие можно добавить, а магазины к нему только через пляску с бубном

**Comment by SkiTles55** [comment]
Помечу себе на будущее, но пока что реализация откладывается, т.к есть более приоритетные вещи
